apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: main-app
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo 'Main application is running'; sleep 10; done"]
        