apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: fluentd-sidecar
spec:
  selector:
    matchLabels:
      app: my-app
  containers:
  - name: fluentd-agent
    image: fluent/fluentd:v1.14
    volumeMounts:
    - name: config-volume
      mountPath: /etc/fluent/
  volumes:
  - name: config-volume
    configMap:
      name: fluentd-config